// plese use this object for fill in resume
const tempcv = {
  id: 8,
  givenName: "",
  familyName: "",
  dateOfBirth: "",
  avatar: "",
  jobTitle: "",
  phone: "",
  email: "",
  streetAddress: "",
  website: "",
  minSalary: "",
  maxSalary: "",
  about: "",
  description: "",
  hobbies: [],
  additionalInfo: "",
  publications: "",
  gender: { id: 1, title: "Male" },
  degree: { id: 5, title: "Short-cycle tertiary education" },
  drivingLicense: { id: 18, title: "B1" },
  nationality: { id: 75, title: "German" },
  industry: { id: 96, title: "Information Technology and Services" },
  residentCountry: { id: 83, title: "Germany" },
  userEducations: [],
  userExperiences: [],
  userExpertises: [],
  userPortfolios: [],
  userSkils: [],
  userLanguages: [],
  userExtraActivities: [],
  userCourses: [],
  userInterships: [],
  userReferences: [],
  userAwards: [],
  userSocials: [],
  banner: "",
};
export default tempcv;
